manifest_path: deployment/quickstart-k8s-deployment
namespace: train-ticket

resource_overrides:
  # - kind: Service
  #   name: ts-gateway-service
  #   patch:
  #     spec:
  #       type: NodePort
  #       ports:
  #         - port: 18888
  #           targetPort: 18888
  #           nodePort: 32677

exclude_resource_patterns:
  - "(^|/)zipkin($|[-/])"
  - "(^|/)skywalking($|[-/])"
  - "(^|/)elasticsearch($|[-/])"